api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

when@dev:
    api_platform:
        defaults:
            cache_headers:
                max_age: 0
                shared_max_age: 0
                vary: ['Content-Type', 'Authorization', 'Origin']
