run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - bodyclose
    - unconvert
    - unparam
    - goconst
    - gocritic
    - gocyclo
    - dupl
    - copyloopvar
    - whitespace

issues:
  exclude-dirs:
    - tmp
    - vendor

  max-issues-per-linter: 0
  max-same-issues: 0

errcheck:
  check-blank: true

gocyclo:
  min-complexity: 15

goconst:
  min-len: 3
  min-occurrences: 2