services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    app.event.authentication_success_listener:
        class: App\Infrastructure\Auth\Listener\AuthenticationSuccessListener
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_authentication_success,
                  method: onAuthenticationSuccessResponse,
              }
    
    app.event.jwt_created_listener:
        class: App\Infrastructure\Auth\Listener\JWTCreatedListener
        tags:
            - {
                  name: kernel.event_listener,
                  event: lexik_jwt_authentication.on_jwt_created,
                  method: onJWTCreated,
              }
